sudo: required
services:
  - docker
before_install:
  - docker build -t guanxin43/react-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true guanxin43/react-test npm test
after_success:
  - docker build -t guanxin43/multi-client ./client
  - docker build -t guanxin43/multi-nginx ./nginx
  - docker build -t guanxin43/multi-server ./server
  - docker build -t guanxin43/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push guanxin43/multi-client
  - docker push guanxin43/multi-nginx
  - docker push guanxin43/multi-server
  - docker push guanxin43/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-612372821785
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
